// src/styles/GlobalStyles.js

import { StyleSheet, Dimensions } from 'react-native';

const windowHeight = Dimensions.get('window').height;
const windowWidth = Dimensions.get('window').width;

export const globalStyles = StyleSheet.create({
  gradientBg: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    minHeight: windowHeight,
    paddingBottom: 24,
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    padding: 0,
  },
  header: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 48,
    paddingBottom: 20,
    backgroundColor: 'rgba(255,234,168,0.10)',
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    shadowColor: '#F54A38',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 8,
    elevation: 4,
    marginBottom: 8,
  },
  headerIconWrapper: {
    backgroundColor: 'rgba(35,36,42,0.3)',
    borderRadius: 40,
    padding: 18,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: '#F54A38',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIcon: {
    width: 56,
    height: 56,
    resizeMode: 'contain',
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFEEA8',
    letterSpacing: 1.2,
    fontFamily: 'System',
    textAlign: 'center',
    marginBottom: 0,
    marginTop: 2,
  },
  userIdText: {
    fontSize: 12,
    color: '#FFEEA8',
    textAlign: 'center',
    marginBottom: 10,
    fontFamily: 'System',
  },
  userIdValue: {
    fontFamily: 'System',
    backgroundColor: '#23242A',
    color: '#F54A38',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#F54A38',
  },
  metricsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginBottom: 16,
    marginTop: 8,
    gap: 8,
  },
  metricsContainerCompact: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginBottom: 12,
    marginTop: 8,
    gap: 8,
  },
  metricCard: {
    backgroundColor: '#161316',
    borderRadius: 20,
    padding: 14,
    margin: 4,
    alignItems: 'center',
    shadowColor: '#F54A38',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 8,
    elevation: 3,
    flexBasis: '46%',
    minWidth: 140,
    maxWidth: '48%',
    borderWidth: 1.5,
    borderColor: '#F54A38',
  },
  metricTitle: {
    fontSize: 13,
    color: '#FFEEA8',
    marginBottom: 4,
    fontWeight: '600',
    fontFamily: 'System',
  },
  metricValue: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#fff',
    fontFamily: 'System',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 18,
    flexWrap: 'wrap',
    gap: 8,
  },
  startButton: {
    backgroundColor: '#F54A38',
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 22,
    marginHorizontal: 4,
    shadowColor: '#F54A38',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    minWidth: 90,
  },
  pauseButton: {
    backgroundColor: '#23242A',
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 22,
    marginHorizontal: 4,
    shadowColor: '#F54A38',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1.5,
    borderColor: '#F54A38',
    minWidth: 90,
  },
  resumeButton: {
    backgroundColor: '#F54A38',
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 22,
    marginHorizontal: 4,
    shadowColor: '#F54A38',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    minWidth: 90,
  },
  stopButton: {
    backgroundColor: '#EC3434',
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 22,
    marginHorizontal: 4,
    shadowColor: '#EC3434',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    minWidth: 90,
  },
  resetButton: {
    backgroundColor: '#23242A',
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 22,
    marginHorizontal: 4,
    shadowColor: '#F54A38',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1.5,
    borderColor: '#F54A38',
    minWidth: 90,
  },
  buttonText: {
    color: '#FFEEA8',
    fontSize: 15,
    fontWeight: 'bold',
    fontFamily: 'System',
    textAlign: 'center',
  },
  mapSection: {
    marginBottom: 28,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFEEA8',
    marginBottom: 8,
    textAlign: 'center',
    letterSpacing: 0.2,
    fontFamily: 'System',
  },
  mapTypeSwitcher: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    marginTop: 2,
  },
  mapTypeButton: {
    backgroundColor: '#23242A',
    paddingVertical: 7,
    paddingHorizontal: 18,
    borderRadius: 18,
    marginHorizontal: 4,
    borderWidth: 1.5,
    borderColor: '#F54A38',
  },
  mapTypeButtonActive: {
    backgroundColor: '#F54A38',
    borderColor: '#F54A38',
  },
  mapTypeButtonText: {
    color: '#F54A38',
    fontWeight: '600',
    fontSize: 13,
    fontFamily: 'System',
  },
  mapTypeButtonTextActive: {
    color: '#23242A',
  },
  mapCard: {
    backgroundColor: '#161316',
    borderRadius: 28,
    overflow: 'hidden',
    shadowColor: '#F54A38',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 16,
    elevation: 6,
    marginHorizontal: 8,
    marginBottom: 18,
    borderWidth: 1.5,
    borderColor: '#F54A38',
    height: windowHeight * 0.28,
    minHeight: 180,
    maxHeight: 320,
  },
  mapCardTracking: {
    height: windowHeight * 0.45,
    minHeight: 300,
    maxHeight: 450,
    marginBottom: 12,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  mapStatusText: {
    textAlign: 'center',
    marginTop: 10,
    fontSize: 12,
    color: '#FFEEA8',
    fontFamily: 'System',
  },
  historySection: {
    flex: 1,
    marginTop: 18,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  noHistoryText: {
    textAlign: 'center',
    color: '#FFEEA8',
    marginTop: 16,
    fontSize: 14,
    fontFamily: 'System',
  },
  historyList: {
    flex: 1,
    paddingHorizontal: 2,
  },
  historyItem: {
    backgroundColor: '#23242A',
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#F54A38',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#F54A38',
  },
  selectedHistoryItem: {
    borderColor: '#F54A38',
    borderWidth: 2,
    backgroundColor: '#23242A',
  },
  historyItemContent: {
    flex: 1,
  },
  historyItemTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#F54A38',
    marginBottom: 4,
    fontFamily: 'System',
  },
  historyItemDetail: {
    fontSize: 13,
    color: '#F54A38',
    fontFamily: 'System',
  },
  centerButton: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    backgroundColor: '#F54A38',
    borderRadius: 30,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  centerButtonInner: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerButtonIcon: {
    fontSize: 24,
  },
  logoutButton: {
    backgroundColor: '#23242A',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#F54A38',
    marginLeft: 10,
  },
  logoutButtonText: {
    color: '#F54A38',
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'System',
  },
});