// src/styles/ShareActivityStyles.js

import { StyleSheet, Dimensions, Platform } from 'react-native';

const windowHeight = Dimensions.get('window').height;
const windowWidth = Dimensions.get('window').width;

export const shareStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  closeButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : 20,
    right: 20,
    backgroundColor: '#F54A38',
    borderRadius: 20,
    width: 35,
    height: 35,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  modalScrollViewContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  shareCardWrapper: {
    width: '100%',
    maxWidth: 500,
    aspectRatio: 9 / 16,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 2,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  shareCard: {
    flex: 1,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  shareCardContent: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
  },
  shareMapContainer: {
    flex: 1.2,
    width: '100%',
    overflow: 'hidden',
  },
  shareMap: {
    width: '100%',
    height: '100%',
  },
  metricsScrollView: {
    flex: 1,
  },
  shareMetricsScrollContentInner: {
    flexGrow: 1,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  shareTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#F54A38',
    marginBottom: 8,
    fontFamily: 'System',
    textAlign: 'center',
  },
  shareDate: {
    fontSize: 14,
    color: '#aaa',
    marginBottom: 12,
    fontFamily: 'System',
    textAlign: 'center',
  },
  shareRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginBottom: 6,
  },
  shareMetricItem: {
    alignItems: 'center',
    flex: 1,
    paddingHorizontal: 5,
  },
  shareMetricValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    fontFamily: 'System',
    textAlign: 'center',
  },
  shareMetricLabel: {
    fontSize: 11,
    color: '#aaa',
    fontFamily: 'System',
    textAlign: 'center',
  },
  shareSourceContainer: {
    alignItems: 'center',
    marginTop: 15,
  },
  shareLogo: {
    width: 95,
    height: 45,
    resizeMode: 'contain',
    marginBottom: 5,
  },
  shareSourceText: {
    fontSize: 13,
    color: '#FFEEA8',
    fontWeight: 'bold',
    fontFamily: 'System',
    letterSpacing: 0.5,
  },
  backgroundOptionsContainer: {
    marginTop: 20,
    width: '100%',
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFEEA8',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'System',
  },
  optionButtonsScroll: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionButton: {
    backgroundColor: '#23242A',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 20,
    marginHorizontal: 5,
    borderWidth: 1.5,
    borderColor: '#F54A38',
  },
  optionButtonActive: {
    backgroundColor: '#F54A38',
  },
  optionButtonText: {
    color: '#F54A38',
    fontWeight: '600',
    fontSize: 13,
    fontFamily: 'System',
  },
  optionButtonTextActive: {
    color: '#23242A',
  },
  clearBackgroundOptionButton: {
    backgroundColor: '#EC3434',
    borderColor: '#EC3434',
  },
  opacitySliderContainer: {
    width: '100%',
    paddingHorizontal: 0,
    marginTop: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  opacityLabel: {
    fontSize: 14,
    color: '#FFEEA8',
    marginRight: 10,
    fontFamily: 'System',
  },
  slider: {
    flex: 1,
    height: 40,
  },
  opacityValue: {
    fontSize: 14,
    color: '#FFEEA8',
    marginLeft: 10,
    fontFamily: 'System',
  },
  downloadButton: {
    backgroundColor: '#F54A38',
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 25,
    marginTop: 20,
    shadowColor: '#F54A38',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    width: '100%',
    alignItems: 'center',
  },
  downloadButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'System',
  },
  modalBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  successModalContent: {
    backgroundColor: '#161316',
    borderRadius: 15,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#F54A38',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    borderWidth: 2,
    borderColor: '#F54A38',
  },
  successIcon: {
    width: 65,
    height: 35,
    marginBottom: 15,
    resizeMode: 'contain',
  },
  successIconPlaceholder: {
    fontSize: 40,
    color: '#28a745',
    marginBottom: 10,
  },
  successText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    fontFamily: 'System',
    textAlign: 'center',
  },
});